"""correct student&group

Revision ID: 752a634797cb
Revises: 2c71b3313b3a
Create Date: 2023-02-26 13:54:11.281423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '752a634797cb'
down_revision = '2c71b3313b3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('students_group_id_fkey', 'students', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('students_group_id_fkey', 'students', 'groups', ['group_id'], ['id'])
    op.alter_column('students', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
